USE videoclub;
DROP FUNCTION IF EXISTS act11;

DELIMITER //
CREATE FUNCTION act11(peCodiPeli SMALLINT UNSIGNED) 
       RETURNS SMALLINT UNSIGNED
       DETERMINISTIC
BEGIN
   DECLARE QtatExemplars SMALLINT UNSIGNED;

   SELECT   COUNT(*)
        INTO QtatExemplars
   FROM     EXEMPLARS
   WHERE    id_peli = peCodiPeli;

   RETURN QtatExemplars;
END//
DELIMITER ;

